### PR TITLE
Use `Z3Solver >> #release` instead of `#del`

### PR DESCRIPTION
**Pull request by janvrany**
MA commit cceedbd removed `#del` in favor of `#release`. This commit catches up to use the latter.

### CODE REVIEW

**Comment by janvrany** [comment]
CI fails because 
```
    self assert: constituents size equals: 3.
```

fails. That's because encoding is `BV32:(concat (concat (concat #b000011 to) #b01100) #x3039)`.
Indeed, `encoding simplify` yields `BV32:(concat #b000011 to #b011000011000000111001)`


@shingarov Do you recall, did we change something in MA that drops that `simplify` somewhere?

**Comment by shingarov** [comment]
So merging #36 did NOT fix CI.  Actually I would be surprised if it did.  ArchC is massively broken at this point; I need to dedicate some love to it.
> did we change something in MA that drops that `simplify` somewhere?

We absolutely did, as part of the PLE chain of commits.  That `simplify` is a very deep rabbit hole.  I believe its investigation is blocked by integrating Nikolaj's fix to "wrong arity".  Which is blocked by Settings (or what was that thing called).  Which, IIRC, was blocked by Ref Counting (or was it?)

**Comment by janvrany** [comment]
> We absolutely did, as part of the PLE chain of commits.

Ah, of course, thanks!

**Comment by janvrany** [comment]
> ArchC is massively broken at this point; I need to dedicate some love to it.

Let's delay this a a bit before having a conversation about it. There're a number of cases where the current design make things bit awkward.

**Pull request merged**
