### PR TITLE
Cleanup Pharo extras

### PR DESCRIPTION
**Pull request by janvrany**
This PR cleans up ArchC-Pharo-Extras so it loads again to Pharo and changes baseline to load it.

### CODE REVIEW

**Comment by shingarov** [comment]
I am not sure I want ArchC-Extras-Pharo loaded by default.  I would rather prefer all that questionable `Cly*` cruft and fragile changes to the base system to get cleaned up (meaning, mostly killed perhaps?) before we do something like `4bcbc48`.

How about we split `4bcbc48` off this branch and have it pending until these Extras get cleaned up?

**Comment by janvrany** [comment]
>  cruft and fragile changes to the base system to get cleaned up (meaning, mostly killed perhaps?)

I'm all for it. This is mostly your code done for TA-Cog experiments. This cleanup was prompted mainly by 2bdf222 and 'ArchC-Extras-Pharo' seem to be natural place for this kind of things.

**Comment by shingarov** [comment]
These *are* mostly-TA-Cog experiments; that's why they are not loaded by default.  Now that I am squinting at `2bdf222` I think it should just live in the class definition (not in an extension) simply because this is what we do for the other GT methods.

**Comment by janvrany** [comment]
I dropped 4bcbc48 and added new commit that moved GT extras to classes package.

**Pull request merged**
